- name: update apt
  apt: update_cache=yes
  ignore_errors: true
  tags:
    - redis_update

- name: ensure packages installed
  apt: pkg={{ item }} state=latest
  with_items:
    - make
    - build-essential
    - tcl8.5

- name: download latest stable redis
  get_url: url=http://download.redis.io/redis-stable.tar.gz dest=/tmp/redis-stable.tar.gz

- name: untar redis
  command: tar zxf /tmp/redis-stable.tar.gz -C /tmp

- name: build redis
  command: make -C /tmp/redis-stable

- name: create redis group
  group: name=redis state=present system=yes

- name: create redis user
  user: name=redis group=redis createhome=no shell=/bin/false system=yes state=present

- name: make sure that /etc/redis exists
  file: path=/etc/redis state=directory mode=0755

- name: make sure that /var/db/redis exists
  file: path=/var/db/redis state=directory mode=0755 group=redis owner=redis

- name: Creates redis log Dir
  file: path=/var/log/redis/ state=directory owner=redis group=redis mode=0775

- name: make sure redis.log file exists
  file: path=/var/log/redis/redis.log state=touch owner=redis group=redis mode=0644

- name: copy upstart file
  copy: src=templates/upstart.conf dest=/etc/init/redis.conf

- name: copy redis.conf file
  copy: src=templates/redis.conf.j2 dest=/etc/redis/redis.conf group=redis owner=redis

- name: Creates redis conf Dir
  file: path=/etc/redis/conf.d/ state=directory owner=redis group=redis mode=0775

- name: copy custom template
  template: src=templates/redis.local.conf.j2 dest=/etc/redis/conf.d/local.conf group=redis owner=redis

- name: copy redis-local script
  template: src=templates/redis-local.j2 dest=/usr/bin/redis-local mode=0755

- name: installing redis binaries
  command: cp /tmp/redis-stable/src/{{ item }} /usr/bin
  with_items: 
    - redis-server
    - redis-cli
    - redis-check-aof
    - redis-check-dump
  notify:
    - restart redis

- name: cleaning up build files
  command: rm -rf /tmp/{{ item }}
  with_items:
    - redis-stable
    - redis-stable.tar.gz
